In [7]:
from numpy import linalg as LA
import numpy as np
a = np.array([[3, 1, 2], [1, 4, 1],[2, 1, 3]])
w, v = LA.eigh(a)
w,v

(array([1., 3., 6.]),
 array([[ 7.07106781e-01,  4.08248290e-01, -5.77350269e-01],
        [-3.59775559e-16, -8.16496581e-01, -5.77350269e-01],
        [-7.07106781e-01,  4.08248290e-01, -5.77350269e-01]]))

In [10]:
import numpy as np
v = [[1,2,3],
     [2,3,4]]
v = np.array(v)
print(v @ v.T)
np.mat((v @ v.T)[0,0])

[[14 20]
 [20 29]]


matrix([[14]])

In [1]:
import numpy as np

def compute_RBF(mat1, mat2, sigma):
    '''
    mat1：数据格式为 n*d1 的矩阵；
    mat2：数据格式为 n*d2 的矩阵；
    sigma：高斯函数的分母标准差
    '''
    trnorms1 = np.mat([(v @ v.T) for v in mat1]).T
    trnorms2 = np.mat([(v @ v.T) for v in mat2]).T
    k1 = trnorms1 @ np.mat(np.ones((mat2.shape[0], 1), dtype=np.float64)).T
    k2 = np.mat(np.ones((mat1.shape[0], 1), dtype=np.float64)) @ trnorms2.T
    k = k1 + k2
    k -= 2 * np.mat(mat1 @ mat2.T)
    k *= - 1./(2 * np.power(sigma, 2))
    return np.exp(k)

mat1 = [[1,2,3],
        [2,3,4]]
mat1 = np.array(mat1)
mat2 = [[4,5,6],
        [5,6,7]]
mat2 = np.array(mat2)

sigma = 0.1
compute_RBF(mat1,mat2,sigma)


matrix([[0.00000000e+000, 0.00000000e+000],
        [2.65039655e-261, 0.00000000e+000]])